LSports/Areas/Tickets/Controllers/DepartmentController.cs
using System.Web.Mvc;
using LSports.Framework.DataAccess.Repositories;
using LSports.Framework.DataAccess.Repositories.Interfaces;
using LSports.Framework.Models.CustomClasses;

namespace LSports.Areas.Tickets.Controllers
{
    //[Authorize(Roles = TicRoles.Admin)]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository _departmentRepository;
        private readonly IUserDepartmentRepository _userDepartmentRepository;

        public DepartmentController() : this(new DepartmentRepository())
        {
        }


        public DepartmentController(IDepartmentRepository departmentRepository)
        {
            _departmentRepository = departmentRepository;
            _userDepartmentRepository = new UserDepartmentRepository();
        }


        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Central()
        {
            return View();
        }


        public JsonResult List()
        {
            var list = _departmentRepository.GetList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Update(Department record)
        {
            _departmentRepository.Update(record);
            return Json(record);
        }



        [HttpPost]
        public JsonResult Insert(Department record)
        {
            _departmentRepository.Insert(record);
            return Json(record);
        }


        [HttpPost]
        public JsonResult Delete(int id)
        {
            _departmentRepository.Delete(id);
            return Json("0");
        }



        [HttpPost]
        public JsonResult ListForDepartment(int id)
        {
            return Json(_userDepartmentRepository.GetListByDepartmentId(id), JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Method to update UserDepartments. 
        /// </summary>
        /// <param name="data">Collection of UserDepartments to add/delete/update. It also contains Department Data</param>
        /// <returns></returns>
        public ActionResult UpdateUserDepartments(UserDepartmentCollectionForDepartment data)
        {
            _userDepartmentRepository.Update(data);
            return Json("Ok");
        }


        //public ActionResult AddDepartmentWithUserDepartments(UserDepartmentCollectionForDepartment data)
        //{
        //    return Json("Ok");
        //}
    }
}

LSports/Areas/Tickets/Controllers/IssueTypeController.cs
using System.Web.Mvc;
using LSports.Framework.DataAccess.Repositories;
using LSports.Framework.DataAccess.Repositories.Interfaces;
using LSports.Framework.Models;
using LSports.Framework.Models.CustomClasses;

namespace LSports.Areas.Tickets.Controllers
{
    [Authorize]
    public class IssueTypeController : Controller
    {
        private readonly IIssueTypeRepository _issueTypeRepository;

        public IssueTypeController() : this(new IssueTypeRepository())
        {
        }

        public IssueTypeController(IIssueTypeRepository issueTypeRepository)
        {
            _issueTypeRepository = issueTypeRepository;
        }

        public ActionResult Index()
        {
            if (User.IsInRole(TicRoles.Staff) || User.IsInRole(TicRoles.CustomerContact))
            {
                return RedirectToAction("Index", "Ticket");
            }

            return View();
        }

        public ActionResult Central()
        {
            return View();
        }

        public JsonResult List()
        {
            var list = _issueTypeRepository.GetList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Update(IssueType record)
        {
            _issueTypeRepository.Update(record);
            return Json(record);
        }


        [HttpPost]
        public JsonResult Insert(IssueType record)
        {
            _issueTypeRepository.Insert(record);
            return Json(record);
        }


        [HttpPost]
        public JsonResult Delete(int id)
        {
            _issueTypeRepository.Delete(id);
            return Json("0");
        }
    }
}

LSports/Areas/Tickets/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LSports.Framework.DataAccess.Repositories;
using LSports.Framework.DataAccess.Repositories.Interfaces;
using LSports.Framework.Models;
using LSports.Framework.Models.CustomClasses;
using LSports.Framework.Models.Enums;
using LSports.Services;
using LSports.Services.Interfaces;
using LSports.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace LSports.Areas.Tickets.Controllers
{
    [Authorize(Roles = TicRoles.Staff + "," + TicRoles.CustomerContact +","+TicRoles.Admin)]
    public class TicketController : Controller
    {

        

        private IList<ControlEnum> GetMockControls(TicketModel ticket, string userId, IList<string> userRoles)
        {
            return _ticketService.GetTicketButtonsAndControls(ticket, userId, userRoles);
            /*var result = new List<ControlEnum>();
            result.Add(ControlEnum.BtnEditTicket);
            result.Add(ControlEnum.BtnReply);
            result.Add(ControlEnum.BtnComment);
            result.Add(ControlEnum.BtnAssignToAnotherDepartment);
            result.Add(ControlEnum.BtnAssignToAnotherUser);
            result.Add(ControlEnum.BtnUnassign);
            result.Add(ControlEnum.BtnReopenTicket);
            result.Add(ControlEnum.BtnCloseTicket);
            result.Add(ControlEnum.LblAssignedTo);
            result.Add(ControlEnum.BtnAssgnToMe);

            return result;*/

        }

        private TicketScreenViewModel PrepareTicketScreenViewModel(TicketLog log, int ticketId, string userId,
            IList<string> roles)
        {
            var ticket = _ticketRepository.GetTicketById(ticketId);
            var showCustomerDetails = !ticket.DepartmentId.HasValue || _departmentRepository.GetItemById(ticket.DepartmentId.Value).CanSeeCustomerDetails;
            var result = new TicketScreenViewModel
            {
                Log = log,
                Ticket = ticket,
                CustomFieldValues = _ticketRepository.GetCustomFieldValues(ticketId),
                Attchments = _ticketRepository.GetTicketAttachedFiles(ticketId),
                ShowCustomerDetails = showCustomerDetails,
            };
            result.Controls = GetMockControls(result.Ticket, userId, UserManager.GetRoles(userId));

            if (roles.Contains(TicRoles.Staff) || roles.Contains(TicRoles.Admin))
            {
                result.InstructionsTextHtml = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
                result.InstructionsLinksHtml = "<div class=\"col - lg - 11\"><a>Quick link 1</a></ div > ";
            }

            return result;
        }


        private readonly ITicketService _ticketService;
        private readonly ITicketRepository _ticketRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly ITicketLogRepository _ticketLogRepository;
        private readonly IFormTemplateRepository _formTemplateRepository;
        private readonly IUserRepository _userRepository;
        private readonly IUserDepartmentRepository _userDepartmentRepository;
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public TicketController() : this(new TicketRepository(), new FormTemplateRepository(), new UserDepartmentRepository(), new TicketLogRepository(), new TicketService(), new UserRepository(), new DepartmentRepository())
        {
        }

        public TicketController(ITicketRepository ticketRepository, IFormTemplateRepository formTemplateRepository, IUserDepartmentRepository userDepartmentRepository, ITicketLogRepository ticketLogRepository, ITicketService ticketService, IUserRepository userRepository, IDepartmentRepository departmentRepository)
        {
            _ticketRepository = ticketRepository;
            _formTemplateRepository = formTemplateRepository;
            _userDepartmentRepository = userDepartmentRepository;
            _ticketLogRepository = ticketLogRepository;
            _ticketService = ticketService;
            _userRepository = userRepository;
            _departmentRepository = departmentRepository;
        }

        public ActionResult Index(int? ticketId)
        {
            var user = _userRepository.GetUserByName(HttpContext.User.Identity.Name);
            var userDepartments = _userDepartmentRepository.GetListByUserId(user.Id);

            var model = _ticketService.GetTicketsModelForStaff(userDepartments, user);

            ViewBag.tickets = model;

            ViewBag.userDepartments = userDepartments;

            return View();
        }


        public JsonResult TicketInstructionsAndCustomFields(int ticketId)
        {
            var userId = User.Identity.GetUserId();
            var result = PrepareTicketScreenViewModel(new TicketLog(), ticketId, userId, UserManager.GetRoles(userId));

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Central()
        {
            //ViewBag.IsCustomer = HttpContext.User.IsInRole(TicRoles.CustomerContact);
            return View();
        }

        public ActionResult AhaFileAttachment()
        {
            return View();
        }

        public ActionResult CreateTicketWizard()
        {
            return View();
        }



        public JsonResult TicketsUpdated(long secondsAgo)
        {
            var ticketIds = _ticketRepository.GetUpdatedTickets(DateTime.Now.AddSeconds(-secondsAgo));
            
            return Json(ticketIds.Count > 0, JsonRequestBehavior.AllowGet);
        }


        // GET: TicketType
        public JsonResult List(int? departmentId, string status, string assignee)
        {
            var result = _ticketService.GetTicketsModelByFilters(departmentId, status, assignee, HttpContext.User.IsInRole(TicRoles.Admin));

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetTicketLogs(int ticketId)
        {
            var ticket = _ticketRepository.GetTicketById(ticketId);
            var department = _departmentRepository.GetItemById(ticket.DepartmentId??0);

            var result = _ticketLogRepository.GetList(ticketId, HttpContext.User.IsInRole(TicRoles.CustomerContact), !department.CanSeeCustomerDetails && !HttpContext.User.IsInRole(TicRoles.Admin));

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public JsonResult EditTicketFields(int ticketId)
        {
            var result = _ticketService.GetTicketFields(ticketId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetAttachedFiles(int ticketId)
        {
            var result = _ticketRepository.GetTicketAttachedFiles(ticketId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public async Task<JsonResult> Update(TicketModel record)
        {
            await _ticketService.UpdateTicket(record);

            return Json(record);
        }


        [HttpPost]
        public  JsonResult Insert(TicketModel record)
        {
            var result = _ticketService.CreateBlankTicket(record);

            return Json(result);
        }



        public JsonResult Controls(int ticketId)
        {
            var userId = User.Identity.GetUserId();
            return Json(GetMockControls(_ticketRepository.GetTicketById(ticketId), userId, UserManager.GetRoles(userId)), JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public JsonResult Delete(int id)
        {
            _ticketRepository.Delete(id);
            return Json("0");
        }


        [HttpPost]
        public async Task<JsonResult> CloseTicket(TicketModel ticket, string comment, int? statusId)
        {
            var log = await _ticketService.CloseTicket(ticket, comment, statusId);

            var userId = User.Identity.GetUserId();
            var result = PrepareTicketScreenViewModel(log, ticket.Id, userId, UserManager.GetRoles(userId));

            return Json(result);
        }


        [HttpPost]
        public async Task<JsonResult> AssignToAnotherUser(int ticketId, string userId, string comment)
        {
            var log = await _ticketService.AssignToAnotherUser(ticketId, userId, comment);

            var userGiud = User.Identity.GetUserId();
            var result = PrepareTicketScreenViewModel(log, ticketId, userGiud, UserManager.GetRoles(userId));

            return Json(result);
        }


        [HttpPost]
        public async Task<JsonResult> AssignToAnotherDepartment(int ticketId, int departmentId, string comment)
        {
            var log = await _ticketService.AssignToAnotherDepartment(ticketId, departmentId, comment);

            var userId = User.Identity.GetUserId();
            var result = PrepareTicketScreenViewModel(log, ticketId, userId, UserManager.GetRoles(userId));

            return Json(result);
        }


        [HttpPost]
        public async Task<JsonResult> AddStaffReply(int ticketId, string reply)
        {
            var log = await _ticketService.AddStaffReply(ticketId, reply);

            var userId = User.Identity.GetUserId();
            var result = PrepareTicketScreenViewModel(log, ticketId, userId, UserManager.GetRoles(userId));

LSports/Areas/Tickets/Controllers/TicketTypeController.cs
using System.Web.Mvc;
using LSports.Framework.DataAccess.Repositories;
using LSports.Framework.DataAccess.Repositories.Interfaces;
using LSports.Framework.Models.CustomClasses;

namespace LSports.Areas.Tickets.Controllers
{
    public class TicketTypeController : Controller
    {
        private readonly ITicketTypeRepository _ticketTypeRepository;

        public TicketTypeController() : this(new TicketTypeRepository())
        {
        }

        public TicketTypeController(ITicketTypeRepository ticketTypeRepository)
        {
            _ticketTypeRepository = ticketTypeRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Central()
        {
            return View();
        }

        // GET: TicketType
        public JsonResult List()
        {
            var list = _ticketTypeRepository.GetList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Update(TicketType record)
        {
            _ticketTypeRepository.Update(record);
            return Json(record);
        }


        [HttpPost]
        public JsonResult Insert(TicketType record)
        {
            _ticketTypeRepository.Insert(record);
            return Json(record);
        }


        [HttpPost]
        public JsonResult Delete(int id)
        {
            _ticketTypeRepository.Delete(id);
            return Json("0");
        }
    }
}

LSports/Areas/Tickets/Views/Shared/DashboardSidebar.cshtml
@using LSports.Framework.Models
@{
    Layout = null;
}

<div class="page-sidebar-wrapper">
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        @*<div style="position: fixed; max-height: 95%; min-height: 95%;  overflow-y: scroll;">*@
        <div>
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu " data-auto-scroll="true" data-slide-speed="200">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
            <!--<li class="sidebar-toggler-wrapper">
                <div class="sidebar-toggler">
                </div>
            </li>-->
            <li style="height: 32px"></li>
            <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
            @if (HttpContext.Current.User.IsInRole(TicRoles.Admin))
            {
                <li class="heading">
                    <h3 class="uppercase">admin</h3>
                </li>
                <li class="">
                    <a href="#par" id="parent" data-toggle="collapse" class="nav-link nav-toggle">
                        <i class="fa fa-cogs"></i>
                        <span class="title">Customize Tickets</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="aha-sub-menu collapse" id="par">
                        <li>
                            <a href="@Url.Action("Index", "IssueType")">
                                Issue Types
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "TicketType")">
                                Ticket Types
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "CustomField")">
                                Custom Fields
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "FormTemplate")">
                                Form Templates
                            </a>
                        </li>
                        <li @*class="active"*@>
                            <a href="@Url.Action("Index", "EmailTemplate")">
                                Email Templates
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "TicketWorkflow")">
                                Ticket Workflow
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#par1" data-toggle="collapse" id="parent1" class="nav-link nav-toggle">
                        <i class="icon-users"></i>
                        <span class="title">Staff & Departments</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="aha-sub-menu collapse" id="par1">
                        <li>
                            <a href="@Url.Action("Index", "Department")">
                                Departments
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "StaffManagement")">
                                Staff
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="heading">
                    <h3 class="uppercase">Tickets</h3>
                </li>
            }



            @if (HttpContext.Current.User.IsInRole(TicRoles.Staff) || HttpContext.Current.User.IsInRole(TicRoles.Admin))
            {

                <li class="" ng-repeat="menuItem in ctrl.sideMenu track by $index">
                    <a href={{"#_par1"+$index}} data-toggle="collapse" class="nav-link nav-toggle" id={{"_parent1"+$index}}>
                        <i class="fa fa-envelope"></i>
                        <span class="title">{{menuItem.Title+" "}} ({{menuItem.Count}})</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="aha-sub-menu collapse" id={{"_par1"+$index}}>
                        <li ng-repeat="menuSubitem in menuItem.Subitems track by $index">
                            <a href="{{menuSubitem.Url}}">
                                {{menuSubitem.Title+" "}} ({{menuSubitem.Count}})
                            </a>
                        </li>
                    </ul>
                </li>
            }

            @if (HttpContext.Current.User.IsInRole(TicRoles.CustomerContact))
            {
                <li class="">
                    <ul class="sub-menu open" style="display: block !important;">

                        <li>
                            <a href="@Url.Action("Index", "Ticket")">
                                Tickets
                            </a>
                        </li>
                    </ul>
                </li>
            }


        </ul>
            <!-- END SIDEBAR MENU -->
            </div>
    </div>
</div>